Traceback (most recent call last):
  File "pretrain.py", line 102, in <module>
    main()
  File "pretrain.py", line 28, in main
    model = {
  File "/home/gauffrea/Projects/SMABalancingGroups/models.py", line 120, in __init__
    self.init_model_(self.data_type, text_optim="sgd", arch=self.hparams['arch'])
  File "/home/gauffrea/Projects/SMABalancingGroups/models.py", line 141, in init_model_
    self.network = CustomResNet(arch=arch, n_classes=self.n_classes, contrastive=self.contrastive)
  File "/home/gauffrea/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ERM' object has no attribute 'contrastive'
Traceback (most recent call last):
  File "pretrain.py", line 102, in <module>
    main()
  File "pretrain.py", line 28, in main
    model = {
  File "/home/gauffrea/Projects/SMABalancingGroups/models.py", line 120, in __init__
    self.init_model_(self.data_type, text_optim="sgd", arch=self.hparams['arch'])
  File "/home/gauffrea/Projects/SMABalancingGroups/models.py", line 141, in init_model_
    self.network = CustomResNet(arch=arch, n_classes=self.n_classes, contrastive=self.contrastive)
  File "/home/gauffrea/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ERM' object has no attribute 'contrastive'